# Base configs
#baseurl: "https://joebrew.net"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
#google_analytics: "UA-46465113-2"

# UI configs
title: "Castells, Festa Major, Santa Coloma de Queralt"
subtitle: "capital del blat"
author: "Joe Brew"
header:
 title: "Castells"
 subtitle: "Santa Coloma de Queralt"
footer:
 name: "Santa Coloma de Queralt"
 bio: "Santa Coloma de Queralt: La Capital del Blat. Festival 2019."
 github: "<a href=\"https://joebrew.net\">here</a>."
social_urls:
  facebook: "https://www.facebook.com/josephbrew"
  twitter: "https://www.twitter.com/joethebrew"
  instagram: "https://www.instagram.com/brew.joe"
  linkedin: "https://linkedin.com/in/joe-brew-1061a33a/"
  github: "https://www.github.com/joebrew"
